#  Restaurant.destroy_all
# rest1 = Restaurant.create(name: "Shake Shack", location: "NYC", cuisine: "Fast Food")
# rest2 = Restaurant.create(name: "Jean Georges", location: "Upper West Side", cuisine: "French")
# rest3 = Restaurant.create(name: "Mercer Kitchen", location: "SoHo", cuisine: "Fast Casual French")
# rest4 = Restaurant.create(name: "ABC Kitchen", location: "Flatiron District", cuisine: "French American")
# rest5 = Restaurant.create(name: "The Connaught", location: "London", cuisine: "French")
# rest6 = Restaurant.create(name: "Perry St", location: "West Village", cuisine: "French-Asian Fusion")
# rest7 = Restaurant.create(name: "ABC Cocina", location: "Flatiron", cuisine: "Latin American-French")
# rest8 = Restaurant.create(name: "Nougatine", location: "Upper West Side", cuisine: "French Casual")
# rest9 = Restaurant.create(name: "Public Kitchen", location: "Lower East Side", cuisine: "French-American")
# rest10 = Restaurant.create(name: "JoJo", location: "Upper East Side", cuisine: "French")
# rest11 = Restaurant.create(name: "JG", location: "NYC", cuisine: "French Upscale")
# rest12 = Restaurant.create(name: "The Mark", location: "Upper East Side", cuisine: "Classic French")
# rest13 = Restaurant.create(name: "ABCV", location: "Flatiron", cuisine: "Vegan")
# rest14 = Restaurant.create(name: "The Fulton", location: "South St Seaport", cuisine: "French-seafood")